src/accounts/urls.py
from django.urls import path
from accounts.views import signup,profile,profile_edit
app_name='job'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('signup/',signup,name='signup'),
    path('profile/',profile,name='profile'),
    path('profile/edit/',profile_edit,name='profile_edit'),
    
]

src/job/urls.py
# from django.contrib import admin
from django.urls import path
from job.views import job_details,job_list,add_job
from . import views
from . import api
from .api import job_list_api,job_detail_api,JobListApi,JobDetail
app_name='job'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',job_list,name='job_list'),
    path('add/',add_job,name='add_job'),
    path('<str:slug>',job_details,name='job_detail'),
    
    # api
    path('api/list/',job_list_api,name='job_list_api'),
    path('api/jobs/<int:id>',job_detail_api,name='job_detail_api'),
    
    # class  passed views
    path('api/v2/jobs/',JobListApi.as_view(),name='JobListApi'),
    path('api/v2/jobs/<int:id>',JobDetail.as_view(),name='JobDetail'),
    
]

src/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('admin/', admin.site.urls),
    path('job/',include('job.urls',namespace='jobs')),
    path('',include('home.urls',namespace='home')),
    path('api-auth/', include('rest_framework.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
# class profile(models.Model):
#     user=models.OneToOneField(User,  on_delete=models.CASCADE)
#     phone_number=models.CharField(max_length=15)
#     image=models.ImageField( upload_to='profile/')
#     city=models.ForeignKey('city',related_name='user_city',on_delete=models.CASCADE,null=True,blank=True)
    
    
#     def __str__(self):
#         return str(self.user)
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15)
    image  = models.ImageField(upload_to='profile/')
    city = models.ForeignKey('City', related_name='user_city', on_delete=models.CASCADE , blank=True, null=True)


    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        
    
    


class city(models.Model):
    name=models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

src/accounts/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class SignUpForm(UserCreationForm):
    class Meta:
        model = User 
        fields=['username','email','password1','password2']
    
    

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields =['username','first_name','last_name','email']
    
    
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields=['city','image','phone_number']

src/accounts/views.py
from django.urls import reverse
from django.shortcuts import render,redirect
from .forms import SignUpForm,UserForm,ProfileForm
from django.contrib.auth import authenticate,login
from .models import Profile
from django.contrib.auth.models import User
# Create your views here.

def signup(request):
    if request.method=='POST':
        form=SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile')
    else:
        form=SignUpForm()
    return render(request,'registration/signup.html',{'form':form})


def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile': profile})


def profile_edit(request):
    profile= Profile.objects.get(user=request.user)
    if request.method=='POST':
        userform=UserForm(request.POST,instance=request.user)
        profileform=ProfileForm(request.POST,request.FILES,instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile= profileform.save(commit=False)
            myprofile.user =request.user
            myprofile.save()
            return redirect(reverse('accounts:profile'))
    else:
        userform=UserForm(instance=request.user)
        profileform=ProfileForm(instance=profile)
    return render(request,'accounts/profile_edit.html',{'userform':userform,'profileform':profileform})

src/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <img width="90px" class="mb-2"  src="{{profile.image.url}}" alt="">
                            <ul>
                                {% comment %} <li><span><img width="80px" height="80px" src="{{profile.image.url}}" alt=""></span></li> {% endcomment %}
                                <li>Name: <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}} </span></li>
                                <li>Phone: <span>{{profile.phone_number}}</span></li>
                                <li>city: <span>{{profile.city}}</span></li>
                                
                            </ul>
                            
                        </div>
                        <div class="p-3">
                            <a class="btn btn-primary mb-2" href="{% url 'accounts:profile_edit'%}">Edit Profile</a>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        {% comment %} <span>Share at:</span> {% endcomment %}
                        <span>My accounts:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}

src/accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">

        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Edit profile</h4>
                        
                            <form  method="post"  enctype='multipart/form-data'>
                                {% csrf_token %}
                                {% bootstrap_form userform %}
                                {% bootstrap_form profileform %}
                                {% buttons %}
                                    <button class="btn btn-primary" type="submit">Edit Now</button>
                                {% endbuttons %}
                            </form> 
                            
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    {% endblock body %}