src/job/urls.py
# from django.contrib import admin
from django.urls import path
from job.views import job_details,job_list,add_job
from . import views
from . import api
from .api import job_list_api,job_detail_api,JobListApi,JobDetail
app_name='job'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',job_list,name='job_list'),
    path('add/',add_job,name='add_job'),
    path('<str:slug>',job_details,name='job_detail'),
    
    # api
    path('api/list/',job_list_api,name='job_list_api'),
    path('api/jobs/<int:id>',job_detail_api,name='job_detail_api'),
    
    # class  passed views
    path('api/v2/jobs/',JobListApi.as_view(),name='JobListApi'),
    path('api/v2/jobs/<int:id>',JobDetail.as_view(),name='JobDetail'),
    
]

src/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('admin/', admin.site.urls),
    path('job/',include('job.urls',namespace='jobs')),
    path('',include('home.urls',namespace='home')),
    path('api-auth/', include('rest_framework.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/job/models.py
import email
from turtle import title
from unicodedata import name
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.


JOB_TYPE=(
    ('Full Time','Full Time'),
    ('part Time','part Time'),
)

def image_upload(instance,filename):
    imagename,extension = filename.split(".")
    return "jobs/%s.%s"%(instance.id,extension)

class Job(models.Model):
    owner=models.ForeignKey(User,related_name='job_owner',on_delete=models.CASCADE)
    title=models.CharField(max_length=100) 
    job_type=models.CharField(max_length=15,choices=JOB_TYPE)
    description=models.TextField(max_length=1000)
    publish_at=models.DateTimeField(auto_now=True)
    vacancy=models.IntegerField(default=1)
    salary=models.IntegerField(default=0)
    experience=models.IntegerField(default=1)
    category=models.ForeignKey('category',on_delete=models.CASCADE,)
    image=models.ImageField(upload_to=image_upload)
    slug=models.SlugField(null=True,blank=True)
    

    def save(self,*args, **kwargs):
        self.slug=slugify(self.title)
        super(Job,self).save(*args, **kwargs)

    def __str__(self) :
        return self.title
    

class category(models.Model):
    name=models.CharField(max_length=25)
    
    def __str__(self) :
        return self.name
    
    
    



class apply(models.Model):
    Job=models.ForeignKey(Job,related_name='apply_job',on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    email=models.EmailField(max_length=100)
    website=models.URLField()
    cv=models.FileField(upload_to='apply/')
    cover_letter=models.TextField(max_length=500)
    created_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

src/job/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms


from .models import apply,Job

class ApplyForm(forms.ModelForm):
    class Meta:
        # db_table = ''
        # managed = True
        # verbose_name = 'ModelName'
        # verbose_name_plural = 'ModelNames'
        model= apply 
        fields=['name','email','website','cv','cover_letter']



class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = '__all__'
        exclude=('slug','owner',)

src/job/views.py
from urllib import request
from django.urls import reverse
from multiprocessing import context
from django.shortcuts import render,redirect
from .models import Job,apply
from django.core.paginator import Paginator
from .forms import ApplyForm,JobForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .filters import JobFilter
# Create your views here.


def job_list(request):
    job_list=Job.objects.all()
    # filter
    myfilter=JobFilter(request.GET,queryset=job_list)
    job_list=myfilter.qs
    paginator = Paginator(job_list, 4) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    
    # return render(request, 'list.html', {'page_obj': page_obj})
    # context ={'jobs':job_list}
    
    context ={'jobs':page_obj,'myfilter':myfilter}
    return render(request,'job/job_list.html',context)



def job_details(request,slug):
    job_detail=Job.objects.get(slug=slug)
    
    if request.method=='POST':
        form=ApplyForm(request.POST,request.FILES)
        print('test')
        if form.is_valid():
            
            myform = form.save(commit=False)
            myform.Job=job_detail
            myform.save()
            # form_test.created_by = request.user
            # form_test.save()
            print('done')
    else:
        form= ApplyForm()
    
    context ={'job': job_detail,'form':form}
    return render(request,'job/job_detail.html',context)

@login_required
def add_job(request):
    
    if request.method=='POST':
        form=JobForm(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.owner=request.user
            myform.save()
            # return render(request,'job/job_list.html',)
            return redirect(reverse('jobs:job_list'))
    else:
        form=JobForm()
    
    return render(request,'job/add_job.html',{'form':form})

src/job/templates/job/add_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add New Job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    {% comment %} <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img width="80px" height="80px" src="{{job.image.url}}" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i> {{job.jab_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div> {% endcomment %}
                    {% comment %} <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.description}}</p>
                        </div>
                    </div> {% endcomment %}
                    <div class="apply_job_form white-bg">
                        <h4>Post New  Job</h4>
                        
                            <form  method="post"  enctype='multipart/form-data'>
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                {% buttons %}
                                    <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                                {% endbuttons %}
                            </form> 
                            {% comment %} <div class="row">
                                <div class="col-md-6">
                                    <div class="input_field">
                                        <input type="text" placeholder="Your name">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input_field">
                                        <input type="text" placeholder="Email">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <input type="text" placeholder="Website/Portfolio link">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button type="button" id="inputGroupFileAddon03"><i class="fa fa-cloud-upload" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" id="inputGroupFile03" aria-describedby="inputGroupFileAddon03">
                                            <label class="custom-file-label" for="inputGroupFile03">Upload CV</label>
                                        </div>
                                        </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <textarea name="#" id="" cols="30" rows="10" placeholder="Coverletter"></textarea>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                    </div>
                                </div>
                            </div>  {% endcomment %}
                            {% comment %} <button class="boxed-btn3 w-100" type="submit">Apply Now</button> {% endcomment %}
                    </div>
                </div>
                {% comment %} <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.publish_at|date:'d M o'}}</span></li>
                                <li>Vacancy: <span>{{job.vacancy}} position</span></li>
                                <li>Salary: <span>{{job.salary}} k/y</span></li>
                                <li>Location: <span>California, USA</span></li>
                                <li>Job Nature: <span> {{job.jab_type}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                            function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                    {
                                    featureType: "all",
                                    stylers: [
                                        { saturation: -90 },
                                        { lightness: 50 }
                                    ]
                                    },
                                    {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                    center: {lat: -31.197, lng: 150.744},
                                    zoom: 9,
                                    styles: grayStyles,
                                    scrollwheel:  false
                                });
                            }
                            
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                            
                        </div>
                    </div>
                </div> {% endcomment %}
            </div>
        </div>
    </div>
    {% endblock body %}

src/job/templates/job/job_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img width="80px" height="80px" src="{{job.image.url}}" alt=""> 
                                    {% comment %} <img width="80px" height="80px" src="{% ststic 'media/jobs/1.jpg' %}" alt=""> {% endcomment %}
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i> {{job.jab_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.description}}</p>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        
                            <form  method="post"  enctype='multipart/form-data'>
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                {% buttons %}
                                    <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                {% endbuttons %}
                            </form>
                            {% comment %} <div class="row">
                                <div class="col-md-6">
                                    <div class="input_field">
                                        <input type="text" placeholder="Your name">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input_field">
                                        <input type="text" placeholder="Email">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <input type="text" placeholder="Website/Portfolio link">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button type="button" id="inputGroupFileAddon03"><i class="fa fa-cloud-upload" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" id="inputGroupFile03" aria-describedby="inputGroupFileAddon03">
                                            <label class="custom-file-label" for="inputGroupFile03">Upload CV</label>
                                        </div>
                                        </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <textarea name="#" id="" cols="30" rows="10" placeholder="Coverletter"></textarea>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                    </div>
                                </div>
                            </div> {% endcomment %}
                        
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.publish_at|date:'d M o'}}</span></li>
                                <li>Vacancy: <span>{{job.vacancy}} position</span></li>
                                <li>Salary: <span>{{job.salary}} k/y</span></li>
                                <li>Location: <span>California, USA</span></li>
                                <li>Job Nature: <span> {{job.job_type}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }
                              
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                            
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}
   

src/job/templates/job/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
    

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{jobs|length}}+ Jobs Available</h3>
                        {% comment %} <h3>{{jobs.count}}+ Jobs Available</h3> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                                {% bootstrap_form myfilter.form %}
                                <input type="submit" value="search" class="boxed-btn3 w-100 mt-3"  />
                            </form>
                        </div>
                        {% comment %} <div class="range_wrap">
                            <label for="amount">Price range:</label>
                            <div id="slider-range"></div>
                            <p>
                                <input type="range" id="amount" readonly style="border:0; color:#7A838B; font-size: 20px; font-weight:600;">
                            </p>
                        </div> {% endcomment %}
                        {% comment %} <div class="reset_btn">
                            <button  class="boxed-btn3 w-100" type="submit">Reset</button> {% endcomment %}
                        {% comment %} </div> {% endcomment %}
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for job in jobs %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img style=""width="80px" height="80px" src="{{job.image.url}}" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'jobs:job_detail' job.slug %}"><h4>{{job}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> Egypt, Cairo</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'jobs:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line: {{job.publish_at|date:'d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        {% if jobs.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                            {% if jobs.has_previous %}
                                                <li><a href="?page={{jobs.previous_page_numbr}}"> <i class="ti-angle-left"></i> </a></li>
                                            {% endif %}
                                            {% for i in jobs.paginator.page_range %}
                                                {% comment %} {% if jobs.number == i %} {% endcomment %}
                                                    <li><a href="?page={{i}}"><span>0{{i}}</span></a></li>
{% comment %} 
                                            {% else %}
                                
                                                <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li> {% endcomment %}
                                
                                            {% endfor %}
                                            {% comment %} <li><a href="#"><span>02</span></a></li> {% endcomment %}
                                            {% if jobs.has_next %}
                                            <li><a href="?page={{jobs.next_page_numbr}}"> <i class="ti-angle-right"></i> </a></li>
                                                {% comment %} <li><a href="?page={{jobs.next_page_numbr}}"> <i class="ti-angle-right"></i> </a></li> {% endcomment %}
                                                {% comment %} <li><a href="?page={{jobs.next_page_numbr}}"> <i class="ti-angle-right"></i> </a></li> {% endcomment %}
                                            {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
    {% endblock body %}
    